### ISSUE TITLE
Make it mobile responsive

### ISSUE THREAD

**Issue by AggRag** [AggRag/UMusic#1]

**Comment by MSTEWARDSON** [comment]
Can I work on this issue?

**Comment by AggRag** [comment]
Yes, please go ahead and work on this.

**Comment by MSTEWARDSON** [comment]
With the way the left and right column div's are setup viewing on mobile could be quite cluttered. Would it be fine If I added a button to tab between the playlist section and the search section of the webpage? Or would you like both the playlist and search portions visible at all times?

**Comment by MSTEWARDSON** [comment]
I have made a pull request with my changes to fix this issue. You can find it here: [05af99b](https://github.com/AggRag/UMusic/pull/2/commits/05af9b5abf748358d0a3efe731b8e6a934f0f5b9)
